### ISSUE TITLE
chromedriver can't get past login page

### ISSUE THREAD

**Issue by groeneveld** [hrenfroe/yahoo-groups-backup#1]
I've been able to start the yahoo-groups-backup program with the following config:
python3 yahoo-groups-backup.py scrape_messages --driver=chrome mygroup

It opens chrome and types in my username, then throws this exception:
splinter.exceptions.ElementDoesNotExist: no elements could be found with name "password"

If I manually click login, it then proceeds to type in my password, but then it can't get past there:
AttributeError: 'ElementList' object has no attribute 'click'

**Comment by hrenfroe** [comment]
Well, that was a gigantic derp on my part. Try with 0313759 (latest master).

**Comment by groeneveld** [comment]
Thanks a bunch! Appears to be working now.
