### ISSUE TITLE
Line 56 syntax error

### ISSUE THREAD

**Issue by torqx** [hrenfroe/yahoo-groups-backup#10]
I installed from the main branch and saw this same error So I've tried this branch: Im running MX Linux (debian-stretch). Something I am missing?

`$ ./yahoo-groups-backup.py -h
  File "./yahoo-groups-backup.py", line 56
    result = {**default_args, **cfg_args}
               ^
SyntaxError: invalid syntax`

Same error all other commands

**Comment by hrenfroe** [comment]
What version of Python are you running? This script requires >= 3.5.

**Comment by torqx** [comment]
> What version of Python are you running? This script requires >= 3.5.
`$ python3.5
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>`

**Comment by torqx** [comment]
> What version of Python are you running? This script requires >= 

> 3.5.

Apparently that is the problem. Although I had installed python3.5 from the distros python2.7 was my default version. Both versions installed at /usr/bin/
 I added this line to ~/bash.rc 

> alias python=/usr/bin/python3.5

so now when I type into a terminal:
`$ python --version`
`Python 3.5.3`
But your script still produces the error mentioned  above.

I probably should have ORIGINALLY done an **alt**install of 3.5 to /usr/**local**/bin
But since I didn't and I do not want to break my system by trying to uninstall python3.5 (i get broken packages error) I will leave things as they are.
Sorry about my **noob** mistakes.
**_Thank You_** @hrenfroe  for your efforts in making these free apps.

**Comment by torqx** [comment]
Thanks Again!
