### ISSUE TITLE
scrape_files does not work correctly

### ISSUE THREAD

**Issue by beebopkim** [hrenfroe/yahoo-groups-backup#11]
When I tried to do scrape_files, it stored file metadata well, but the actual file content was wrong. The content of every scraped files is exactly same wrong content and same size though I cannot recognize what it is.

**Comment by hrenfroe** [comment]
It sounds like the scraper is picking up an error instead of file content. Can you share one of the files and/or the group name, if it's public?

**Comment by hrenfroe** [comment]
You can also try an alternate tool https://github.com/IgnoredAmbience/yahoo-group-archiver and possibly a more up-to-date fork at https://github.com/ArchiveTeam/yahoo-group-archiver . I'm not up to speed on the development process there so it may or may not work for you.

**Comment by beebopkim** [comment]
Thanks but the group I want to backup is not public.

If I know Python and Selenium well, I would change this backup program by myself, but honestly I do not know it well, so I would try another backup program.

Thank you.
