### ISSUE TITLE
Feature Request: Start scrape at specific message number

### ISSUE THREAD

**Issue by groeneveld** [hrenfroe/yahoo-groups-backup#4]
During a large scrape the yahoo api goes down sometimes and crashes the backup program. I need a way to start it back where it left off.

**Comment by hrenfroe** [comment]
How many messages are in the group? The script should detect and skip messages that it's already scraped, but if you have several hundred thousand I can see it taking a while to pick back up.

**Comment by groeneveld** [comment]
Ah you're right! My bad.
